"use client";

import { useMemo } from "react";
import { useQuery } from "convex/react";
import { BarChart3, TrendingUp, Tag, Activity } from "lucide-react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts";

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { ScreenHeader, LoadingPanel } from "@/components/dashboard/screen-kit";
import { dashboardApi } from "@/components/dashboard/data";
import { useWorkspace } from "@/components/dashboard/workspace-context";

export function SalesAnalyticsScreen() {
  const { organization } = useWorkspace();
  const analytics = useQuery(
    dashboardApi.ecommerce.getSalesAnalytics,
    organization ? { organizationId: organization._id } : "skip"
  );

  const { chartData, topProducts, kpis } = useMemo(() => {
    if (!analytics || !organization) {
      return { chartData: [], topProducts: [], kpis: null };
    }

    let totalRevenue = 0;
    let totalDiscount = 0;
    const salesByDate: Record<string, number> = {};
    const salesByProduct: Record<string, { name: string; revenue: number; units: number }> = {};

    analytics.events.forEach((event) => {
      totalRevenue += event.revenueMinor;
      totalDiscount += event.discountPercentage; // We'll average this later

      // Group by date for chart
      const dateStr = new Date(event.createdAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
      salesByDate[dateStr] = (salesByDate[dateStr] || 0) + (event.revenueMinor / 100);

      // Group by product
      if (!salesByProduct[event.offeringId]) {
        salesByProduct[event.offeringId] = {
          name: event.offeringName || "Unknown",
          revenue: 0,
          units: 0,
        };
      }
      salesByProduct[event.offeringId].revenue += (event.revenueMinor / 100);
      salesByProduct[event.offeringId].units += 1;
    });

    const dates = Object.keys(salesByDate);
    // If no data, provide a mock layout structure
    const mappedChartData = dates.length > 0 
      ? dates.map(date => ({ date, revenue: salesByDate[date] }))
      : [{ date: "No data", revenue: 0 }];

    const mappedTopProducts = Object.values(salesByProduct)
      .sort((a, b) => b.units - a.units)
      .slice(0, 5);

    const formatCurrency = (amount: number) => {
      return new Intl.NumberFormat(organization.locale || "en-US", {
        style: "currency",
        currency: organization.currency || "USD",
        maximumFractionDigits: 0,
      }).format(amount / 100);
    };

    return {
      chartData: mappedChartData,
      topProducts: mappedTopProducts,
      kpis: {
        totalOrders: analytics.events.length,
        totalRevenueFormatted: formatCurrency(totalRevenue),
        avgDiscount: analytics.events.length > 0 
          ? Math.round(totalDiscount / analytics.events.length) 
          : 0,
      }
    };
  }, [analytics, organization]);

  if (!analytics || !organization) {
    return (
      <>
        <ScreenHeader
          eyebrow="Performance"
          title="Sales Analytics"
          description="Analyze the sales and negotiation performance of your AI receptionist."
        />
        <LoadingPanel rows={5} />
      </>
    );
  }

  return (
    <>
      <ScreenHeader
        eyebrow="Performance"
        title="Sales Analytics"
        description="Analyze the sales, revenue, and negotiation performance of your AI receptionist."
      />

      <div className="grid gap-4 md:grid-cols-3">
        <Card className="bg-white">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total AI Revenue</CardTitle>
            <TrendingUp className="size-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{kpis?.totalRevenueFormatted}</div>
            <p className="text-xs text-muted-foreground">Generated by AI in the last 30 days</p>
          </CardContent>
        </Card>

        <Card className="bg-white">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Orders</CardTitle>
            <Activity className="size-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{kpis?.totalOrders}</div>
            <p className="text-xs text-muted-foreground">Successfully closed by AI</p>
          </CardContent>
        </Card>

        <Card className="bg-white">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Avg. Discount Given</CardTitle>
            <Tag className="size-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{kpis?.avgDiscount}%</div>
            <p className="text-xs text-muted-foreground">Across negotiated sales</p>
          </CardContent>
        </Card>
      </div>

      <section className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(18rem,0.65fr)]">
        <Card className="bg-white">
          <CardHeader className="border-b border-black/8 pb-4">
            <div className="flex items-center gap-2">
              <BarChart3 className="size-4 text-primary" />
              <CardTitle className="font-heading text-xl tracking-tight">
                Revenue Over Time
              </CardTitle>
            </div>
            <CardDescription className="text-xs">
              Daily revenue generated by the AI (last 30 days).
            </CardDescription>
          </CardHeader>
          <CardContent className="pt-6">
            <div className="h-[300px] w-full">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={chartData} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e5e7eb" />
                  <XAxis 
                    dataKey="date" 
                    axisLine={false}
                    tickLine={false}
                    tick={{ fontSize: 12, fill: "#6b7280" }}
                    dy={10}
                  />
                  <YAxis 
                    axisLine={false}
                    tickLine={false}
                    tick={{ fontSize: 12, fill: "#6b7280" }}
                    tickFormatter={(value) => `$${value}`}
                  />
                  <Tooltip 
                    cursor={{ fill: '#f3f4f6' }}
                    contentStyle={{ borderRadius: '8px', border: '1px solid #e5e7eb', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                  />
                  <Bar dataKey="revenue" fill="#0f766e" radius={[4, 4, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-white">
          <CardHeader className="border-b border-black/8 pb-4">
            <CardTitle className="font-heading text-xl tracking-tight">
              Top Products
            </CardTitle>
            <CardDescription className="text-xs">
              Most units sold by the AI.
            </CardDescription>
          </CardHeader>
          <CardContent className="pt-4">
            {topProducts.length > 0 ? (
              <div className="space-y-4">
                {topProducts.map((product, index) => (
                  <div key={index} className="flex items-center justify-between">
                    <div className="min-w-0 pr-4">
                      <p className="truncate text-sm font-medium">{product.name}</p>
                      <p className="text-xs text-muted-foreground">{product.units} units sold</p>
                    </div>
                    <div className="font-mono text-sm font-medium">
                      ${Math.round(product.revenue)}
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="flex h-32 items-center justify-center text-sm text-muted-foreground">
                No sales data yet.
              </div>
            )}
          </CardContent>
        </Card>
      </section>
    </>
  );
}
